
name: Code Verify

on:
  push:
    branches-ignore: [main, bugfix/GH-19-krew-not-working ]
  pull_request:
    #branches: ['*']
    branches-ignore: [main, bugfix/GH-19-krew-not-working ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21.6'

      - name: Build
        run: go build -v ./...

      - name: Test
        run: go test -p 1 -v ./...
